export const DEFAULT_RECIPES = [
  {
    id: 'r1',
    title: 'HP Tallow, Coconut & Cacao Soap — Citrus Cedar',
    categories: ['Soap', 'Bar Soap', 'Scented'],
    baseServings: 1,
    servingLabel: 'batch',
    description: 'Hot process loaf soap for a 10" x 2.5" x 3.5" silicone-lined mold.',
    ingredients: [
      { id: 'i1', name: 'Tallow', amount: 539, unit: 'g' },
      { id: 'i2', name: 'Coconut oil', amount: 323, unit: 'g' },
      { id: 'i3', name: 'Cacao butter', amount: 215, unit: 'g' },
      { id: 'i4', name: 'NaOH (lye)', amount: 150, unit: 'g' },
      { id: 'i5', name: 'Distilled water', amount: 303, unit: 'g' },
      { id: 'i6', name: 'Sweet orange EO', amount: 19, unit: 'g' },
      { id: 'i7', name: 'Grapefruit EO', amount: 8, unit: 'g' },
      { id: 'i8', name: 'Cedarwood EO', amount: 5, unit: 'g' },
      { id: 'i9', name: 'Yellow cab mica (in 1 tsp oil)', amount: 2, unit: 'tsp' },
      { id: 'i10', name: 'Tangerine mica (in 1 tsp oil)', amount: 1, unit: 'tsp' },
      { id: 'i11', name: 'Gold mica (in 1 tsp oil)', amount: 1, unit: 'tsp' },
    ],
    steps: [
      { id: 's1', title: 'Pre-mix everything', text: 'Set out mold with liner. Pre-mix EOs in a small cup. Mix each mica into 1 tsp light oil separately. Have everything ready before you start.', timer: null },
      { id: 's2', title: 'Make lye solution', text: 'In a ventilated area, pour distilled water into a heat-safe pitcher. Slowly add NaOH to water — never water to lye. Stir until dissolved. Very hot. Cool to ~120°F / 50°C.', timer: 600 },
      { id: 's3', title: 'Melt oils', text: 'Combine tallow, coconut oil, and cacao butter in slow cooker on low. Stir until melted. Cool to ~120°F / 50°C.', timer: 900 },
      { id: 's4', title: 'Stick blend to trace', text: 'Slowly pour lye solution into oils. Stick blend in short bursts until medium trace — thick like pudding. 1-3 minutes.', timer: 180 },
      { id: 's5', title: 'Cook — watch it, yours runs hot', text: 'Cover and cook on low. Check every 10 min, fold edges in. Done in ~20-30 min. Looks glossy and waxy when done. Zap test: touch tiny amount to tongue tip. No zap = done. Pull off heat immediately.', timer: 1500 },
      { id: 's6', title: 'Add color — move fast', text: 'Scoop 2/3 batter into separate bowl. Mix yellow cab + tangerine mica into large portion. Mix gold mica into remaining 1/3. If stiffening, add 1-2 tbsp hot distilled water and stir hard.', timer: null },
      { id: 's7', title: 'Add fragrance', text: 'Add pre-mixed EO blend to orange/yellow portion, stir fast. Stir a little into gold portion too.', timer: null },
      { id: 's8', title: 'Pack the mold', text: 'Alternate spooning orange and gold batter into lined mold. Press firmly to eliminate air pockets. One or two lazy folds for marbled effect. Rustic top is fine.', timer: null },
      { id: 's9', title: 'Unmold and cut', text: 'Unmold after 24 hours. Cut into bars. Usable immediately but cure 2-4 weeks for a harder bar.', timer: 86400 },
    ],
    notes: 'Lye safety: always add lye TO water. Gloves and eye protection always.\nYellow cab mica 2:1 over tangerine — tangerine can go muddy.\nAlways mix micas into a small amount of liquid oil first.\nYield: 10-12 bars depending on cut thickness.',
  },
  {
    id: 'r2',
    title: 'Tallow Balm — Citrus Cedar',
    categories: ['Balm', 'Tallow Balm', 'Scented'],
    baseServings: 9,
    servingLabel: 'tins',
    description: 'Rich tallow balm for 8-10 x 2 oz tins.',
    ingredients: [
      { id: 'i1', name: 'Tallow (rendered, strained)', amount: 227, unit: 'g' },
      { id: 'i2', name: 'Coconut oil (refined)', amount: 85, unit: 'g' },
      { id: 'i3', name: 'Cacao butter', amount: 57, unit: 'g' },
      { id: 'i4', name: 'Sweet orange EO', amount: 15, unit: 'g' },
      { id: 'i5', name: 'Grapefruit EO', amount: 6, unit: 'g' },
      { id: 'i6', name: 'Cedarwood EO', amount: 4, unit: 'g' },
    ],
    steps: [
      { id: 's1', title: 'Prep tins and pre-mix EOs', text: 'Set out tins on a flat level surface. Pre-mix all EOs in a small cup and set aside.', timer: null },
      { id: 's2', title: 'Melt oils together', text: 'Combine tallow, coconut oil, and cacao butter in a double boiler. Stir gently until fully melted. Do not overheat.', timer: 600 },
      { id: 's3', title: 'Cool before adding scent', text: 'Remove from heat. Let cool until no longer steaming and slightly hazy around edges — ~120-130°F / 49-54°C. Too hot and EOs flash off.', timer: 600 },
      { id: 's4', title: 'Add fragrance', text: 'Pour in pre-mixed EO blend and stir gently but thoroughly.', timer: null },
      { id: 's5', title: 'Pour into tins', text: 'Pour slowly into tins, filling just below the rim. Do not move until fully set.', timer: null },
      { id: 's6', title: 'Set at room temperature', text: 'Leave undisturbed until fully set and opaque. Do not refrigerate.', timer: 7200 },
      { id: 's7', title: 'Cap and label', text: 'Cap tins once fully set. Label with name, date, and ingredients.', timer: null },
    ],
    notes: 'Regular coconut oil (not MCT) — MCT stays liquid and makes balm too soft.\nRefined coconut oil = no coconut scent, lets EOs shine.\nShelf life: 6-12 months. Keep lids on.',
  },
  {
    id: 'r3',
    title: 'Blood Orange Hand Sanitizer',
    categories: ['Sanitizer', 'Citrus'],
    baseServings: 1,
    servingLabel: 'batch',
    description: 'DIY hand sanitizer with 91% isopropyl, aloe gel, and citrus EOs. Shake before each use.',
    ingredients: [
      { id: 'i1', name: '91% isopropyl alcohol', amount: 3, unit: 'tbsp' },
      { id: 'i2', name: 'Aloe vera gel', amount: 1, unit: 'tbsp' },
      { id: 'i3', name: 'Sweet orange EO', amount: 7, unit: 'drops' },
      { id: 'i4', name: 'Grapefruit EO', amount: 3, unit: 'drops' },
    ],
    steps: [
      { id: 's1', title: 'Combine', text: 'Pour isopropyl alcohol into a small bowl. Add aloe gel and stir well until fully combined.', timer: null },
      { id: 's2', title: 'Add scent', text: 'Add sweet orange and grapefruit EO drops. Stir to distribute.', timer: null },
      { id: 's3', title: 'Check consistency', text: 'Should be pourable but not watery. Too thin: add a few more drops of aloe. Too thick: add a few more drops of alcohol.', timer: null },
      { id: 's4', title: 'Bottle', text: 'Transfer to a squeeze or pump bottle. Label with contents and date.', timer: null },
    ],
    notes: '3:1 alcohol to aloe keeps final concentration ~68% — above CDC minimum of 60%.\nDo not add more aloe.\nShake before each use.\nShelf life: ~3 months away from heat and sunlight.',
  },
  {
    id: 'r4',
    title: 'Garlic Parmesan Chicken Skewers',
    categories: ['Food', 'Chicken', 'Grilling'],
    baseServings: 4,
    servingLabel: 'servings',
    description: 'Juicy garlic parm skewers with mayo marinade and garlic butter parm sauce. Air fryer or grill.',
    ingredients: [
      { id: 'i1', name: 'Chicken breasts or thighs, cut into 1.5" cubes', amount: 900, unit: 'g' },
      { id: 'i2', name: 'Mayonnaise', amount: 2, unit: 'tbsp' },
      { id: 'i3', name: 'Olive oil', amount: 1, unit: 'tbsp' },
      { id: 'i4', name: 'Paprika', amount: 1, unit: 'tbsp' },
      { id: 'i5', name: 'Garlic powder', amount: 1, unit: 'tsp' },
      { id: 'i6', name: 'Italian seasoning', amount: 1, unit: 'tsp' },
      { id: 'i7', name: 'Red pepper flakes', amount: 0.5, unit: 'tsp' },
      { id: 'i8', name: 'Black pepper', amount: 0.5, unit: 'tsp' },
      { id: 'i9', name: 'Salt', amount: 0.25, unit: 'tsp' },
      { id: 'i10', name: 'Parmesan, finely grated (marinade)', amount: 2, unit: 'tbsp' },
      { id: 'i11', name: 'Unsalted butter', amount: 4, unit: 'tbsp' },
      { id: 'i12', name: 'Garlic cloves, minced', amount: 4, unit: 'cloves' },
      { id: 'i13', name: 'Parmesan, finely grated (sauce)', amount: 3, unit: 'tbsp' },
      { id: 'i14', name: 'Fresh parsley, chopped', amount: 2, unit: 'tbsp' },
      { id: 'i15', name: 'Lemon, juiced', amount: 0.5, unit: 'lemon' },
    ],
    steps: [
      { id: 's1', title: 'Make marinade and coat chicken', text: 'Combine mayo, olive oil, paprika, garlic powder, Italian seasoning, red pepper flakes, black pepper, salt, and parmesan. Add chicken and toss until fully coated. Marinate at least 20 min.', timer: 1200 },
      { id: 's2', title: 'Skewer', text: 'Thread chicken onto skewers leaving a small gap between pieces.', timer: null },
      { id: 's3', title: 'Make garlic parm sauce', text: 'Melt butter in small pan. Add minced garlic, cook 1 min. Off heat, stir in parmesan, parsley, and lemon juice. Set aside.', timer: 60 },
      { id: 's4', title: 'Grill', text: 'Medium-high heat. Indirect heat first 5-6 min lid down. Move to direct heat 5-6 more min. Pull at 165°F internal. Rest 3 min.', timer: 720 },
      { id: 's5', title: 'Sauce and serve', text: 'Brush garlic parm butter sauce generously over hot skewers. Hit with extra parmesan and parsley. Serve immediately.', timer: null },
    ],
    notes: 'Mayo is the secret — emulsifies the marinade, helps char without drying out.\nAir fryer option: 390°F for 11 min, flip at 5-6 min.\nFinely grated parm only — coarse won\'t melt properly.',
  },
];

export const CATEGORY_TREE = {
  Food: {
    Chicken: {}, Beef: {}, Seafood: {}, Vegetarian: {}, Pasta: {}, Salad: {},
    Grilling: {},
    Holiday: { Easter: {}, Passover: {}, Thanksgiving: {}, Christmas: {} },
    Mexican: {}, Italian: {}, Asian: {}, Breakfast: {}, Dessert: {}, Soup: {},
  },
  Soap: { 'Bar Soap': {}, 'Shampoo Bar': {}, Scented: {}, Unscented: {}, Vegan: {}, 'Tallow Soap': {} },
  Balm: { 'Tallow Balm': {}, 'Vegan Balm': {}, 'Lip Balm': {}, Scented: {}, Unscented: {}, Healing: {} },
  Sanitizer: { Citrus: {}, Lavender: {}, Unscented: {} },
  Lotion: { 'Body Lotion': {}, Face: {}, 'Hand Cream': {} },
  Scrub: { 'Sugar Scrub': {}, 'Salt Scrub': {} },
};



